/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Actividad13_JPANELIMAGE_MateoAyarra;

import java.awt.Graphics;
import java.io.File;
import java.io.Serializable;
import javax.accessibility.AccessibleContext;
import javax.swing.ImageIcon;

/**
 *
 * @author alumno
 */
public class JPanelImagen extends javax.swing.JPanel implements Serializable{

    private File rutaImg;

    @Override
    public AccessibleContext getAccessibleContext() {
        return super.getAccessibleContext(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        if (rutaImg != null && rutaImg.exists()){
            ImageIcon ImgIcon = new ImageIcon(rutaImg.getAbsolutePath());

            // Tamaño del panel
            int panelWidth = getWidth();
            int panelHeight = getHeight();

            // Tamaño original de la imagen
            int imageWidth = ImgIcon.getIconWidth();
            int imageHeight = ImgIcon.getIconHeight();

            // Escalar la imagen para que siempre quepa en el JPanel manteniendo la proporción
            double imageAspect = (double) imageWidth / imageHeight;
            double panelAspect = (double) panelWidth / panelHeight;

            int newWidth, newHeight;

            // Comparar proporciones para ajustar la imagen
            if (panelAspect < imageAspect) {
                newWidth = panelWidth;
                newHeight = (int) (panelWidth / imageAspect);
            } else {
                newHeight = panelHeight;
                newWidth = (int) (panelHeight * imageAspect);
            }

            // Dibujar la imagen centrada
            int x = (panelWidth - newWidth) / 2;
            int y = (panelHeight - newHeight) / 2;
            
            g.drawImage(ImgIcon.getImage(), 0, 0, null);
        }
    }

    public File getRutaImg() {
        return rutaImg;
    }

    public void setRutaImg(File rutaImg) {
        this.rutaImg = rutaImg;
    }
    
    /**
     * Creates new form JPanelImagen
     */
    public JPanelImagen() {
        initComponents();
    }

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
